version: "3.8"

services:
  postgre:
    restart: always
    build:
      context: .
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - WALE_S3_PREFIX
      - AWS_REGION
    ports:
      - 5432:5432
    volumes:
      - ./.db:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro

  pgadmin:
    restart: always
    image: dpage/pgadmin4
    container_name: postgres_admin
    environment:
      - PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD
    ports:
      - 5435:80